# Generated by Django 5.2.10 on 2026-02-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "spotify_playlist_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=64)),
                ("track_name", models.CharField(max_length=200)),
                ("artists", models.CharField(max_length=200)),
                ("album", models.CharField(blank=True, max_length=200)),
                ("image", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="spotify_app.mood",
                    ),
                ),
            ],
        ),
    ]
