# Generated by Django 5.2.10 on 2026-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=64)),
                ("track_name", models.CharField(max_length=200)),
                ("artists", models.CharField(max_length=200)),
                ("album", models.CharField(blank=True, max_length=200)),
                ("image", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
