# Generated by Django 5.2.10 on 2026-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0002_trackhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="spotify_user_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="spotify_user_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="trackhistory",
            name="spotify_user_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="mood",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="mood",
            unique_together={("spotify_user_id", "name")},
        ),
    ]
