# Generated by Django 5.2.10 on 2026-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0003_mood_spotify_user_id_moodentry_spotify_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_user_id", models.CharField(db_index=True, max_length=64)),
                ("track_id", models.CharField(db_index=True, max_length=64)),
                ("mood", models.CharField(blank=True, max_length=32)),
                ("intensity", models.IntegerField(default=50)),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["spotify_user_id", "seen_at"],
                        name="spotify_app_spotify_f77e3a_idx",
                    ),
                    models.Index(
                        fields=["spotify_user_id", "mood", "intensity", "seen_at"],
                        name="spotify_app_spotify_362081_idx",
                    ),
                ],
                "unique_together": {
                    ("spotify_user_id", "track_id", "mood", "intensity")
                },
            },
        ),
    ]
