# Generated by Django 5.2.10 on 2026-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0004_recommendationseen"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendationseen",
            name="spotify_app_spotify_362081_idx",
        ),
        migrations.AlterUniqueTogether(
            name="recommendationseen",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="recommendationseen",
            name="mode",
            field=models.CharField(default="blend", max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationseen",
            unique_together={
                ("spotify_user_id", "track_id", "mood", "intensity", "mode")
            },
        ),
        migrations.AddIndex(
            model_name="recommendationseen",
            index=models.Index(
                fields=["spotify_user_id", "mood", "intensity", "mode", "seen_at"],
                name="spotify_app_spotify_0f589c_idx",
            ),
        ),
    ]
