# Generated by Django 5.2.10 on 2026-02-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spotify_app",
            "0005_remove_recommendationseen_spotify_app_spotify_362081_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_user_id", models.CharField(db_index=True, max_length=64)),
                ("track_id", models.CharField(db_index=True, max_length=64)),
                ("mood", models.CharField(blank=True, max_length=32)),
                ("intensity", models.IntegerField(default=50)),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "like"), (-1, "dislike")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["spotify_user_id", "mood", "value", "created_at"],
                        name="spotify_app_spotify_7bec84_idx",
                    ),
                    models.Index(
                        fields=["spotify_user_id", "value", "created_at"],
                        name="spotify_app_spotify_c88799_idx",
                    ),
                ],
                "unique_together": {("spotify_user_id", "track_id", "mood")},
            },
        ),
    ]
